---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Popular Pets
description: Create pie charts and bar graphs from data you collect.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Create a Pie Chart
- title: 'Challenge: Create your own bar chart'
  challenge: true
- title: Read data from a file
  completion:
  - engaged
  - internal
- title: 'Challenge: Create a new chart from a file'
  challenge: true
- title: 'Challenge: More charts and graphs!'
  challenge: true
  completion:
  - external
