---
hero_image: images/popular-pets.png
theme: पीला
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: लोकप्रिय पालतू जानवर
description: अपने एकत्रित किए गए डेटा से पाई चार्ट और बार ग्राफ बनाएँ।
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: पशु
technologies: python
site_areas: प्रोजेक्ट
hardware: ''
software: python (पायथन)
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: एक पाई चार्ट बनाएं
  - 
    title: 'चुनौती: अपना खुद का बार ग्राफ बनाएँ'
  - 
    title: फाइल से रोबोट डेटा पढ़ें
  - 
    title: 'चुनौती: एक फ़ाइल से एक नया चार्ट बनाएं'
  - 
    title: 'चुनौती: अधिक चार्ट और रेखांकन!'
