---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Animais de estimação populares
description: Cria gráficos circulares e gráficos de barras a partir dos dados recolhidos.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
- title: Do que vais necessitar
  completion: engaged
- title: Cria um gráfico circular
- title: 'Desafio: cria o teu próprio gráfico de barras'
- title: Ler dados de um ficheiro
- title: 'Desafio: Cria um novo gráfico a partir de um ficheiro'
  completion: internal
- title: 'Desafio: Mais gráficos e tabelas!'
