---
hero_image: images / popular-pets.png
theme: amarelo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-1, phys-comp-0, fabricação-0, comunidade-0
title: Animais de estimação populares
description: Crie gráficos de pizza e gráficos de barra a partir dos dados coletados.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animais
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Crie um gráfico de pizza
  - 
    title: 'Desafio: crie seu próprio gráfico de barras'
  - 
    title: Ler dados de um arquivo
  - 
    title: 'Desafio: crie um novo gráfico a partir de um arquivo'
  - 
    title: 'Desafio: Mais gráficos e tabelas!'
