---
hero_image: images / popular-pets.png
theme: amarelo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-1, phys-comp-0, fabricação-0, comunidade-0
title: Animais de estimação populares
description: Cria gráficos circulares e gráficos de barras a partir dos dados recolhidos.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animais
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que vais precisar
  - 
    title: Cria um gráfico circular
  - 
    title: 'Desafio: cria o teu próprio gráfico de barras'
  - 
    title: Ler dados de um ficheiro
  - 
    title: 'Desafio: Cria um novo gráfico a partir de um ficheiro'
  - 
    title: 'Desafio: Mais gráficos e tabelas!'
