---
hero_image: images / popular-pets.png
theme: amarelo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-1, phys-comp-0, fabricação-0, comunidade-0
title: Animais de estimação populares
description: Create pie charts and bar graphs from data you collect.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animais
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: What you will need
  - 
    title: Create a Pie Chart
  - 
    title: 'Challenge: Create your own bar chart'
  - 
    title: Read data from a file
  - 
    title: 'Challenge: Create a new chart from a file'
  - 
    title: 'Desafio: Mais gráficos e tabelas!'
