---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Mascotas populares
description: Crea gráficos circulares y gráficos de barras a partir de datos recaudados.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Introducción
  - title: Lo que necesitarás
  - title: Crea un Gráfico Circular
  - title: 'Desafío: Crea tu propio gráfico de barras'
  - title: Leer los datos desde un archivo
  - title: 'Desafío: Crea un nuevo gráfico a partir de un archivo'
  - title: 'Desafío: ¡Más cuadros y gráficos!'
