---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Beliebte Haustiere
description: Erstelle Kreis- und Balkendiagramme von den Daten, die du gesammelt hast.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: tiere
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Erstelle ein Kreisdiagramm
  - title: 'Herausforderung: Erstelle dein eigenes Balkendiagramm'
  - title: Daten aus einer Datei auslesen
  - title: 'Herausforderung: Erstelle ein neues Diagramm aus einer Datei'
  - title: 'Herausforderung: Mehr Diagramme und Grafiken!'
