---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Popular Pets
description: Erstelle ein Kreis- oder Balkendiagramm von den Daten, die du gesammelt hast.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: pythons
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Erstelle ein Kreisdiagramm
  - 
    title: 'Aufgabe: Erstelle dein eigenes Balkendiagramm'
  - 
    title: 'Daten von einer Datei ablesen'
  - 
    title: 'Aufgabe: Erstelle ein neues Diagramm aus einer Datei'
  - 
    title: 'Aufgabe: Noch mehr Diagramme und Grafiken!'
  - 
    title: 'Challenge: More charts and graphs!'
