---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: ಜನಪ್ರಿಯ ಸಾಕುಪ್ರಾಣಿಗಳು
description: ನೀವು ಸಂಗ್ರಹಿಸಿದ ಡೇಟಾದಿಂದ ಪೈ ಚಾರ್ಟ್(pie chart) ಮತ್ತು ಬಾರ್ ಗ್ರಾಫ್‌(bar graph) ಗಳನ್ನು ರಚಿಸಿ.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: ಪರಿಚಯ
  - 
    title: ನಿಮಗೆ ಏನು ಬೇಕಾಗುತ್ತದೆ
  - 
    title: ಪೈ ಚಾರ್ಟ್(Pie Chart) ತಯಾರಿಸಿ
  - 
    title: 'ಸವಾಲು: ನಿಮ್ಮ ಸ್ವಂತ ಬಾರ್ ಚಾರ್ಟ್(bar chart) ರಚಿಸಿ'
  - 
    title: file ‌ನಿಂದ ಡೇಟಾವನ್ನು ಓದಿ
  - 
    title: 'ಸವಾಲು: file ‌ನಿಂದ ಹೊಸ ಚಾರ್ಟ್ ರಚಿಸಿ'
  - 
    title: 'ಸವಾಲು: ಹೆಚ್ಚಿನ ಚಾರ್ಟ್(chart) ‌ಗಳು ಮತ್ತು ಗ್ರಾಫ್(graph)‌ಗಳು!'
