---
hero_image: images/popular-pets.png
theme: 노란
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, 디자인 -0, 프로그래밍 -1, phys-comp-0, 제조 -0, 커뮤니티 -0
title: Popular Pets
description: Create pie charts and bar graphs from data you collect.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: 동물
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: Create a Pie Chart
  - 
    title: 'Challenge: Create your own bar chart'
  - 
    title: Read data from a file
  - 
    title: 'Challenge: Create a new chart from a file'
  - 
    title: 'Challenge: More charts and graphs!'
