---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Popularni ljubimci
description: Izradi kružne i stubičaste grafikone od prikupljenih podataka.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Izradi kružni grafikon
  - 
    title: 'Izazov: Izradi sopstveni stubičasti grafikon'
  - 
    title: Čitaj podatke iz datoteke
  - 
    title: 'Izazov: Izradi novi grafikon od podataka iz datoteke'
  - 
    title: 'Izazov: Još grafikona!'
