---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Animaux de compagnie préférés
description: Créer des camemberts et des histogrammes à partir de données que vous collectez.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animaux
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: 'Défi : Créer votre propre camembert'
  - 
    title: 'Défi : Lire des données à partir d''un fichier'
  - 
    title: 'Défi : Créer un nouveau histogramme à partir d''un fichier de données'
  - 
    title: 'Défi : Encore plus d''histogrammes et de camemberts à partir d''un fichier'
  - 
    title: 'Défi: Plus de tableaux et de graphiques!'
