---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Animaux de compagnie préférés
description: Créer des camemberts et des histogrammes à partir de données que tu collectes.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Ce dont tu auras besoin
- title: Créer un camembert
- title: 'Défi : Crée ton histogramme'
- title: Lire les données à partir d'un fichier
  completion:
  - engaged
  - internal
- title: 'Défi : Créer un nouveau graphique à partir d''un fichier'
- title: 'Défi : Plus de tableaux et de graphiques !'
