---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Animali Popolari
description: Crea grafici a torta e a barre dai dati che raccogli.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: animals
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Crea un grafico a torta
  - 
    title: 'Sfida: crea il tuo grafico a barre'
  - 
    title: Carica i dati da un file
    completion:
      - engaged
      - internal
  - 
    title: 'Sfida: crea un nuovo grafico da un file'
  - 
    title: 'Sfida: più grafici e diagrammi!'
