---
hero_image: images/popular-pets.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Popular Pets
description: Create pie charts and bar graphs from data you collect.
original_url: https://codeclubprojects.org/en-GB/python/popular-pets
interests: hayvanlar
technologies: python
site_areas: projeler
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Nelere ihtiyacınız olacak
  - 
    title: Create a Pie Chart
  - 
    title: 'Challenge: Create your own bar chart'
  - 
    title: Read data from a file
  - 
    title: 'Challenge: Create a new chart from a file'
  - 
    title: 'Challenge: More charts and graphs!'
